# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: venue/venue.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'venue/venue.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from risk_engine.proto.instrument import instrument_pb2 as instrument_dot_instrument__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11venue/venue.proto\x12\rsynapse.venue\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1binstrument/instrument.proto\"\x8d\x01\n\x11VenueCapabilities\x12\x1e\n\x16supports_market_orders\x18\x01 \x01(\x08\x12\x1d\n\x15supports_limit_orders\x18\x02 \x01(\x08\x12\x1a\n\x12supports_streaming\x18\x03 \x01(\x08\x12\x1d\n\x15max_orders_per_second\x18\x04 \x01(\x05\"\xe7\x02\n\x0eLiquidityVenue\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12&\n\x04type\x18\x03 \x01(\x0e\x32\x18.synapse.venue.VenueType\x12*\n\x06status\x18\x04 \x01(\x0e\x32\x1a.synapse.venue.VenueStatus\x12\x38\n\x10supported_assets\x18\x05 \x03(\x0e\x32\x1e.synapse.instrument.AssetClass\x12\x16\n\x0elatency_p50_us\x18\x06 \x01(\x03\x12\x16\n\x0elatency_p99_us\x18\x07 \x01(\x03\x12\x11\n\tfill_rate\x18\x08 \x01(\x01\x12\x32\n\x0elast_heartbeat\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x36\n\x0c\x63\x61pabilities\x18\n \x01(\x0b\x32 .synapse.venue.VenueCapabilities*\xa2\x01\n\x0bVenueStatus\x12\x1c\n\x18VENUE_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n\x16VENUE_STATUS_CONNECTED\x10\x01\x12\x1d\n\x19VENUE_STATUS_DISCONNECTED\x10\x02\x12\x19\n\x15VENUE_STATUS_DEGRADED\x10\x03\x12\x1f\n\x1bVENUE_STATUS_AUTHENTICATION\x10\x04*\x8e\x01\n\tVenueType\x12\x1a\n\x16VENUE_TYPE_UNSPECIFIED\x10\x00\x12\x17\n\x13VENUE_TYPE_EXCHANGE\x10\x01\x12\x18\n\x14VENUE_TYPE_DARK_POOL\x10\x02\x12\x18\n\x14VENUE_TYPE_SIMULATED\x10\x03\x12\x18\n\x14VENUE_TYPE_TOKENIZED\x10\x04\x42,Z*github.com/synapse-oms/proto/venue;venuepbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'venue.venue_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*github.com/synapse-oms/proto/venue;venuepb'
  _globals['_VENUESTATUS']._serialized_start=605
  _globals['_VENUESTATUS']._serialized_end=767
  _globals['_VENUETYPE']._serialized_start=770
  _globals['_VENUETYPE']._serialized_end=912
  _globals['_VENUECAPABILITIES']._serialized_start=99
  _globals['_VENUECAPABILITIES']._serialized_end=240
  _globals['_LIQUIDITYVENUE']._serialized_start=243
  _globals['_LIQUIDITYVENUE']._serialized_end=602
# @@protoc_insertion_point(module_scope)
