# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: instrument/instrument.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'instrument/instrument.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1binstrument/instrument.proto\x12\x12synapse.instrument\x1a\x1fgoogle/protobuf/timestamp.proto\"\x88\x01\n\x0fTradingSchedule\x12\x0f\n\x07is_24x7\x18\x01 \x01(\x08\x12\x13\n\x0bmarket_open\x18\x02 \x01(\t\x12\x14\n\x0cmarket_close\x18\x03 \x01(\t\x12\x12\n\npre_market\x18\x04 \x01(\t\x12\x13\n\x0b\x61\x66ter_hours\x18\x05 \x01(\t\x12\x10\n\x08timezone\x18\x06 \x01(\t\"\xe3\x02\n\nInstrument\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x33\n\x0b\x61sset_class\x18\x04 \x01(\x0e\x32\x1e.synapse.instrument.AssetClass\x12\x16\n\x0equote_currency\x18\x05 \x01(\t\x12\x15\n\rbase_currency\x18\x06 \x01(\t\x12\x11\n\ttick_size\x18\x07 \x01(\t\x12\x10\n\x08lot_size\x18\x08 \x01(\t\x12=\n\x10settlement_cycle\x18\t \x01(\x0e\x32#.synapse.instrument.SettlementCycle\x12:\n\rtrading_hours\x18\n \x01(\x0b\x32#.synapse.instrument.TradingSchedule\x12\x0e\n\x06venues\x18\x0b \x03(\t\x12\x17\n\x0fmargin_required\x18\x0c \x01(\t*\xad\x01\n\nAssetClass\x12\x1b\n\x17\x41SSET_CLASS_UNSPECIFIED\x10\x00\x12\x16\n\x12\x41SSET_CLASS_EQUITY\x10\x01\x12\x16\n\x12\x41SSET_CLASS_CRYPTO\x10\x02\x12\"\n\x1e\x41SSET_CLASS_TOKENIZED_SECURITY\x10\x03\x12\x16\n\x12\x41SSET_CLASS_FUTURE\x10\x04\x12\x16\n\x12\x41SSET_CLASS_OPTION\x10\x05*~\n\x0fSettlementCycle\x12 \n\x1cSETTLEMENT_CYCLE_UNSPECIFIED\x10\x00\x12\x17\n\x13SETTLEMENT_CYCLE_T0\x10\x01\x12\x17\n\x13SETTLEMENT_CYCLE_T1\x10\x02\x12\x17\n\x13SETTLEMENT_CYCLE_T2\x10\x03\x42\x36Z4github.com/synapse-oms/proto/instrument;instrumentpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'instrument.instrument_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z4github.com/synapse-oms/proto/instrument;instrumentpb'
  _globals['_ASSETCLASS']._serialized_start=582
  _globals['_ASSETCLASS']._serialized_end=755
  _globals['_SETTLEMENTCYCLE']._serialized_start=757
  _globals['_SETTLEMENTCYCLE']._serialized_end=883
  _globals['_TRADINGSCHEDULE']._serialized_start=85
  _globals['_TRADINGSCHEDULE']._serialized_end=221
  _globals['_INSTRUMENT']._serialized_start=224
  _globals['_INSTRUMENT']._serialized_end=579
# @@protoc_insertion_point(module_scope)
