# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from risk_engine.proto.risk import risk_pb2 as risk_dot_risk__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in risk/risk_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RiskGateStub(object):
    """─── Service ────────────────────────────────────────────────────────

    Synchronous pre-trade risk check — called by Order Gateway before routing
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckPreTradeRisk = channel.unary_unary(
                '/synapse.risk.RiskGate/CheckPreTradeRisk',
                request_serializer=risk_dot_risk__pb2.PreTradeRiskRequest.SerializeToString,
                response_deserializer=risk_dot_risk__pb2.PreTradeRiskResponse.FromString,
                _registered_method=True)


class RiskGateServicer(object):
    """─── Service ────────────────────────────────────────────────────────

    Synchronous pre-trade risk check — called by Order Gateway before routing
    """

    def CheckPreTradeRisk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RiskGateServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckPreTradeRisk': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckPreTradeRisk,
                    request_deserializer=risk_dot_risk__pb2.PreTradeRiskRequest.FromString,
                    response_serializer=risk_dot_risk__pb2.PreTradeRiskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'synapse.risk.RiskGate', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('synapse.risk.RiskGate', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RiskGate(object):
    """─── Service ────────────────────────────────────────────────────────

    Synchronous pre-trade risk check — called by Order Gateway before routing
    """

    @staticmethod
    def CheckPreTradeRisk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/synapse.risk.RiskGate/CheckPreTradeRisk',
            risk_dot_risk__pb2.PreTradeRiskRequest.SerializeToString,
            risk_dot_risk__pb2.PreTradeRiskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
