# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: marketdata/marketdata.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'marketdata/marketdata.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bmarketdata/marketdata.proto\x12\x12synapse.marketdata\x1a\x1fgoogle/protobuf/timestamp.proto\"\xec\x01\n\x12MarketDataSnapshot\x12\x15\n\rinstrument_id\x18\x01 \x01(\t\x12\x10\n\x08venue_id\x18\x02 \x01(\t\x12\x11\n\tbid_price\x18\x03 \x01(\t\x12\x11\n\task_price\x18\x04 \x01(\t\x12\x10\n\x08\x62id_size\x18\x05 \x01(\t\x12\x10\n\x08\x61sk_size\x18\x06 \x01(\t\x12\x12\n\nlast_price\x18\x07 \x01(\t\x12\x12\n\nvolume_24h\x18\x08 \x01(\t\x12\x0c\n\x04vwap\x18\t \x01(\t\x12-\n\ttimestamp\x18\n \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xc8\x01\n\x05OHLCV\x12\x15\n\rinstrument_id\x18\x01 \x01(\t\x12\x0c\n\x04open\x18\x02 \x01(\t\x12\x0c\n\x04high\x18\x03 \x01(\t\x12\x0b\n\x03low\x18\x04 \x01(\t\x12\r\n\x05\x63lose\x18\x05 \x01(\t\x12\x0e\n\x06volume\x18\x06 \x01(\t\x12\x30\n\x0cperiod_start\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nperiod_end\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"F\n\x0eOrderBookLevel\x12\r\n\x05price\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\t\x12\x13\n\x0border_count\x18\x03 \x01(\x05\"\xc7\x01\n\tOrderBook\x12\x15\n\rinstrument_id\x18\x01 \x01(\t\x12\x10\n\x08venue_id\x18\x02 \x01(\t\x12\x30\n\x04\x62ids\x18\x03 \x03(\x0b\x32\".synapse.marketdata.OrderBookLevel\x12\x30\n\x04\x61sks\x18\x04 \x03(\x0b\x32\".synapse.marketdata.OrderBookLevel\x12-\n\ttimestamp\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampB6Z4github.com/synapse-oms/proto/marketdata;marketdatapbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'marketdata.marketdata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z4github.com/synapse-oms/proto/marketdata;marketdatapb'
  _globals['_MARKETDATASNAPSHOT']._serialized_start=85
  _globals['_MARKETDATASNAPSHOT']._serialized_end=321
  _globals['_OHLCV']._serialized_start=324
  _globals['_OHLCV']._serialized_end=524
  _globals['_ORDERBOOKLEVEL']._serialized_start=526
  _globals['_ORDERBOOKLEVEL']._serialized_end=596
  _globals['_ORDERBOOK']._serialized_start=599
  _globals['_ORDERBOOK']._serialized_end=798
# @@protoc_insertion_point(module_scope)
